GET http://localhost:3000/

###

GET http://localhost:3000/api/chores

###

GET http://localhost:3000/api/chores/2784

###

POST http://localhost:3000/api/chores
Content-Type: application/json

{
    "id": 12345,
    "category": "🟢 Sådd/plantering",
    "title": "Så sockerärter i pluggbrätte",
    "time": 30,
    "date": "2021-04-17"
}

###

DELETE http://localhost:3000/api/chores
Content-Type: application/json

{
    "id": 2784,
    "category": "🟡 Rensning",
    "title": "Rensa ogräs i bädd A2",
    "time": 30,
    "date": "2021-04-10"
}

###

PUT http://localhost:3000/api/chores
Content-Type: application/json

{
    "id": 2784,
    "category": "🟡 Rensning",
    "title": "Rensa ogräs i bädd A2 och A4",
    "time": 60,
    "date": "2021-04-25"
}

###